### ISSUE TITLE
BDM | BUG | Card is overlapping with the next section

### ISSUE THREAD

**Issue by Diksha-Beacon** [beacondig/site-beacon#88] opened 2020-10-27 11:37 UTC
**Location of bug**
Seen here: http://2883648-hs-sites-com.sandbox.hs-sites.com/-temporary-slug-1838d8f4-a9a0-4702-9358-299a9dd40aa3?hs_preview=elsQihjr-35713730916

**Describe the bug**
Card is overlapping with the next section!

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e78ca48cfc5ca700cb6ab3a/4d6e8eb9-7482-4c06-9781-cfa686ef84a8)

**Desktop (please complete the following information):**
Common issue for all Windows & macOS.

**Comment by dbeau79** [comment] 2020-11-09 11:16
@Diksha-Beacon - this is by design.  I'll go ahead and close it out.

**Closed by dbeau79** 2020-11-09 11:16 UTC
Labels: Priority: High, Type: Bug
